test "equippable component - equipment slot" when running minecraft "1.21.2":
	set {_item} to player head
	set the equipment slot of {_item} to helmet slot
	assert the equipment slot of {_item} is helmet slot with "Item equipment slot was not set to helmet slot"
	set the equipment slot of {_item} to chest slot
	assert the equipment slot of {_item} is chest slot with "Item equipment slot was not set to chest slot"
	set the equipment slot of {_item} to legs slot
	assert the equipment slot of {_item} is legs slot with "Item equipment slot was not set to legs slot"
	set the equipment slot of {_item} to boots slot
	assert the equipment slot of {_item} is boots slot with "Item equipment slot was not set to boots slot"
	set the equipment slot of {_item} to main hand slot
	assert the equipment slot of {_item} is main hand slot with "Item equipment slot was not set to main hand slot"
	set the equipment slot of {_item} to off hand slot
	assert the equipment slot of {_item} is off hand slot with "Item equipment slot was not set to off hand slot"
