test "new tool rule" when running minecraft "1.20.6":
	###
		Combines:
			ExprNewToolRule
			EffToolRuleDrops
			CondToolRuleDrops
			ExprToolRuleSpeed
			ExprToolRuleBlocks
	###
	set {_rule} to a new tool rule with block types oak log, stone and obsidian
	assert {_rule} is set with "New tool rule was not created"
	assert {_rule} is a tool rule with "New tool rule is not a tool rule"
	assert the tool rule block types of {_rule} is oak log, stone and obsidian with "New tool rule block types did not get set on creation"
	set the tool rule speed of {_rule} to 10
	enable the tool rule drops of {_rule}
	assert the tool rule speed of {_rule} is 10 with "New tool rule speed was not set"
	assert the tool rule drops of {_rule} is enabled with "New tool rule drops are not enabled"
