test "recipe key":
	register a new cooking recipe with the key "test_recipe_key":
		set the input item to raw copper named "test_recipe_key"
		set the result to copper ingot named "test_recipe_key"
	set {_last} to last registered recipe
	set {_get} to recipe with the key "test_recipe_key"
	assert the recipe key of {_last} = "test_recipe_key" with "Key mismatch of last registered recipe"
	assert the recipe key of {_get} = "test_recipe_key" with "Key mismatch of get recipe"
