test "entity unload" when running JUnit:
	set {_test} to "org.skriptlang.skript.test.tests.syntaxes.effects.EffEntityUnloadTest"
	ensure junit test {_test} completes "make despawnable" and "make not despawnable"

	spawn a zombie, a skeleton and a villager at test-location
	make all entities not despawnable on chunk unload
	if all entities can not despawn on chunk unload:
		complete objective "make not despawnable" for {_test}
	force all entities to despawn when far away
	if all entities can despawn when far away:
		complete objective "make despawnable" for {_test}
	clear all entities
