on load:
	set {_test::1} to "got player"
	set {_test::2} to "got reason"
	set {_test::3} to "got new cooldown"

	ensure junit test "org.skriptlang.skript.test.tests.syntaxes.events.EvtExperienceCooldownChangeTest" completes {_test::*}

on player experience cooldown change:
	junit test is "org.skriptlang.skript.test.tests.syntaxes.events.EvtExperienceCooldownChangeTest"
	if event-player is set:
		complete objective "got player" for junit test "org.skriptlang.skript.test.tests.syntaxes.events.EvtExperienceCooldownChangeTest"
	if change reason is plugin:
		complete objective "got reason" for junit test "org.skriptlang.skript.test.tests.syntaxes.events.EvtExperienceCooldownChangeTest"
	if event-timespan is set:
		complete objective "got new cooldown" for junit test "org.skriptlang.skript.test.tests.syntaxes.events.EvtExperienceCooldownChangeTest"

