test "EvtPiglinBarterJUnit" when running JUnit:
	set {_test} to "org.skriptlang.skript.test.tests.syntaxes.events.EvtPiglinBarterTest"

	set {_slashIndex} to last index of "/" in "%script%.sk"
	if {_slashIndex} is -1: # try \ separator (Windows)
		set {_slashIndex} to last index of "\" in "%script%.sk"
	set {_parent} to substring of "%script%.sk" from 0 to {_slashIndex}
	load script "%{_parent}%-EvtPiglinBarter.sk"

	set {_tests::1} to "correct barter input"
	set {_tests::2} to "clear barter drops"
	set {_tests::3} to "set barter drops to 2 items"
	set {_tests::4} to "remove item from barter drops"
	set {_tests::5} to "add multiple items to barter drops"
	set {_tests::6} to "remove all of an item from barter drops"
	set {_tests::7} to "remove multiple items from barter drops"
	set {_tests::8} to "barter drops test complete"
	ensure {_test} completes {_tests::*}
