test "smithing recipe nbt copy" when running minecraft "1.20.0":
	###
		Combines:
			EffSmithingNBT
			CondSmithingNBT
	###
	set {_base} to diamond named "test_smithing_recipe_nbt_copy"
	set {_template} to netherite ingot named "test_smithing_recipe_nbt_copy"
	set {_addition} to emerald named "test_smithing_recipe_nbt_copy"
	set {_recipe} to a new smithing transform recipe with the key "test_smithing_recipe_nbt_copy":
		set the recipe base item to {_base}
		set the recipe template item to {_template}
		set the recipe addition item to {_addition}
		set the recipe result to netherite sword named "test_smithing_recipe_nbt_copy"
		disallow the nbt copying from the base item to the result item
	add {_recipe} to the server's recipes
	set {_get} to recipe with the key "test_smithing_recipe_nbt_copy"
	if running below minecraft "1.20.5":
		assert {_recipe} does not allow nbt copying with "Created recipe should not allow nbt copying"
		assert {_get} does not allow nbt copying with "Retrieved recipe should not allow nbt copying"
