
# Bats require time to go to sleep

test "fox wakeup and sleep":
	spawn a fox at test-location:
		set {_entity} to entity
	make {_entity} goto sleep
	assert {_entity} is sleeping with "Fox should be sleeping"
	make {_entity} wakeup
	assert {_entity} is not sleeping with "Fox should be awake"
	clear entity within {_entity}

test "villager wakeup and sleep":
	set {_old} to block at test-block
	set block at test-block to red bed
	spawn a villager at test-location:
		set {_entity} to entity
	make {_entity} goto sleep at test-block
	assert {_entity} is sleeping with "Villager should be sleeping"
	make {_entity} wakeup
	assert {_entity} is not sleeping with "Villager should be awake"
	clear entity within {_entity}
	set block at test-block to {_old}
