test "zombify villager":
	clear all entities
	spawn 5 villagers at test-location
	assert size of all villagers is 5 with "5 villagers did not spawn"
	zombify all villagers
	assert size of all villagers is 0 with "All villagers should be zombie villagers"
	assert size of all zombie villagers is 5 with "Should be 5 zombie villagers after zombifying villagers"
	unzombify all zombie villagers
	# Requires 2 ticks after unzombifying for proper check
	# assert size of all villagers is 5 with "Should be 5 villagers after unzombifying zombie villagers"
	# assert size of all zombie villagers is 0 with "All zombie villagers should be villagers"
	clear all entities
