test "get entity snapshot" when running minecraft "1.20.2":
	create a new entity snapshot from a pig and store it in {_snapshot}:
		set the max health of entity to 20
		set the health of entity to 20
	assert {_snapshot} is an entity snapshot with "Get entity snapshot is not an entity snapshot"
	spawn {_snapshot} at location(0,0,0):
		set {_entity} to entity
	assert the max health of {_entity} is 20 with "Max health did not stick to the spawned entity"
	assert the health of {_entity} is 20 with "Health did not stick to the spawned entity"
	clear {_entity}

	if running minecraft "1.20.5":
		set {_item} to a zombie spawn egg
		set the spawn egg entity of {_item} to {_snapshot}
		assert the spawn egg entity of {_item} is {_snapshot} with "Spawn egg entity is not stored snapshot"
